version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.security.enabled=false
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic

  kibana:
    image: kibana:7.10.1
    ports:
      - target: 5601
        published: 5601
    volumes:
      - ./kibana/:/usr/share/kibana/config/
    depends_on:
      - elasticsearch
    networks:
      - elastic      


networks:
  elastic:
    name: elastic
    driver: bridge